### ISSUE TITLE
Compatibility w/ latest versions of Homebridge/HOOBS

### ISSUE THREAD

**Issue by mcalderin** [zwaldowski/homebridge-satellite-fan#13]
Installing the plugin doesn't work, presumably due to nodejs-legacy being deprecated.

**Comment by viictor924** [comment]
Damn, I wish I had read this before I formatted my Pi to install HomeBridgeUI. I managed to port all my plug-ins except for this one. 

@mcalderin were you able to find a work-around?

@zwaldowski any chance you can update the plug-in? :D

**Comment by mcalderin** [comment]
No and I'd love to get this working since I have four of the devices.  Haven't had any time to work on it this year.  Hoping @zwaldowski may have some good news.

**Comment by zwaldowski** [comment]
I don't have this hardware anymore. I'm not aware of any express incompatibility, so I could at least look into it and get it running on a Pi. Do either of you have a log or anything from it failing to install?

**Comment by viictor924** [comment]
Hey @zwaldowski thanks for responding.

========================================================================
These are the errors when running Homebridge:
![image](https://user-images.githubusercontent.com/23468631/125541623-a230f403-d701-41b2-9ced-dd068a28bc86.png)

And text version in case you want to copy/paste anything:

[13/07/2021, 17:00:51] Loaded config.json with 2 accessories and 2 platforms.
[13/07/2021, 17:00:51] Loaded 2 cached accessories from cachedAccessories.
[13/07/2021, 17:00:51] ---
[13/07/2021, 17:00:52] Loaded plugin: homebridge-config-ui-x@4.41.1
[13/07/2021, 17:00:52] Registering platform 'homebridge-config-ui-x.config'
[13/07/2021, 17:00:52] ---
[13/07/2021, 17:00:52] Loaded plugin: homebridge-gpio-device@0.4.9
homebridge-gpio-device API version: 2.7
[13/07/2021, 17:00:52] Registering accessory 'homebridge-gpio-device.GPIODevice'
[13/07/2021, 17:00:52] ---
[13/07/2021, 17:00:52] Loaded plugin: homebridge-magichome-dynamic-platform@1.9.2
[13/07/2021, 17:00:52] Registering platform 'homebridge-magichome-dynamic-platform.homebridge-magichome-dynamic-platform'
[13/07/2021, 17:00:52] ---
[13/07/2021, 17:00:52] ====================
[13/07/2021, 17:00:52] ERROR LOADING PLUGIN homebridge-satellite-fan:
[13/07/2021, 17:00:52] Error: Cannot find module 'bluetooth-hci-socket'
Require stack:
- /usr/local/lib/node_modules/homebridge-satellite-fan/node_modules/noble/lib/hci-socket/hci.js
- /usr/local/lib/node_modules/homebridge-satellite-fan/node_modules/noble/lib/hci-socket/bindings.js
- /usr/local/lib/node_modules/homebridge-satellite-fan/node_modules/noble/lib/resolve-bindings.js
- /usr/local/lib/node_modules/homebridge-satellite-fan/node_modules/noble/index.js
- /usr/local/lib/node_modules/homebridge-satellite-fan/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-satellite-fan/node_modules/noble/lib/hci-socket/hci.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
[13/07/2021, 17:00:52] ====================
[13/07/2021, 17:00:52] Loading 2 platforms...
[13/07/2021, 17:00:52] [Config] Initializing config platform...
[13/07/2021, 17:00:52] [Config] Running in Service Mode
[13/07/2021, 17:00:52] [homebridge-magichome-dynamic-platform] Initializing homebridge-magichome-dynamic-platform platform...
[13/07/2021, 17:00:52] [homebridge-magichome-dynamic-platform] Finished initializing homebridge-magichome-dynamic-platform '1.9.2'
[13/07/2021, 17:00:52] [homebridge-magichome-dynamic-platform] If this plugin brings you joy, consider visiting GitHub and giving it a ⭐.
[13/07/2021, 17:00:52] Loading 2 accessories...
[13/07/2021, 17:00:52] No plugin was found for the accessory "satellite-fan" in your config.json. Please make sure the corresponding plugin is installed correctly.
[13/07/2021, 17:00:52] [Gate Buzzer] Initializing GPIODevice accessory...
Preparing Advertiser for 'Homebridge 5A25 9E23' using bonjour-hap backend!
Setup Payload:
X-HM://0023THZS3HBR6
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:

**Comment by viictor924** [comment]
And these are the errors when installing homebridge-satellite-fan 
First I tried "sudo npm install -g homebridge homebridge-satellite-fan"

and got Err code 128. I searched through some old issues on this github and found this issue related to Err 128:
https://github.com/zwaldowski/homebridge-satellite-fan/issues/8

So I tried running "sudo su" and then "sudo npm install -g --unsafe-perm homebridge-satellite-fan", but that didn't work either. 


![image](https://user-images.githubusercontent.com/23468631/125545708-a8d5dcee-ab28-49da-9b6f-4ab7f6425cc2.png)

Text version below:

pi@homebridge:/var/lib/homebridge $ sudo npm install -g homebridge homebridge-satellite-fan
npm ERR! code 128
npm ERR! command failed
npm ERR! command git --no-replace-objects clone https://git@github.com/lockitron/noble.git /root/.npm/_cacache/tmp/git-clone-8032f1f8 --recurse-submodules --depth=1
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-8032f1f8': Permission denied

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-14T01_20_16_416Z-debug.log
pi@homebridge:/var/lib/homebridge $  
pi@homebridge:/var/lib/homebridge $  
pi@homebridge:/var/lib/homebridge $ sudo su
root@homebridge:/var/lib/homebridge# sudo npm install -g --unsafe-perm homebridge-satellite-fan
npm ERR! code 128
npm ERR! command failed
npm ERR! command git --no-replace-objects clone https://git@github.com/lockitron/noble.git /root/.npm/_cacache/tmp/git-clone-af483a91 --recurse-submodules --depth=1
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-af483a91': Permission denied

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-14T01_21_41_805Z-debug.log
root@homebridge:/var/lib/homebridge#

**Comment by viictor924** [comment]
Some more info:

Homebridge: v1.3.4
OS: Raspbian GNU/Linux Buster (10)
Node.js Version: v14.16.1
Npm Version: v7.15.0

**Comment by zwaldowski** [comment]
Yeah, ok, the situation with the Bluetooth module is F.U.B.A.R., but should be resolvable. I don't know that I can do anything with the `.npm` directory, that sounds like a permissions problem on your device.

**Comment by zwaldowski** [comment]
Try installing from `master`: `npm install -g homebridge zwaldowski/homebridge-satellite-fan#master`. I'll publish those changes if it works. (I've looked into Homebridge's updates and there shouldn't be anything incompatible with newer Node or Debian, just that stupid Bluetooth plugin.)

**Comment by viictor924** [comment]
Hey @zwaldowski thanks for the update! 
I tried running `npm install -g homebridge zwaldowski/homebridge-satellite-fan#master` and got this error:
![image](https://user-images.githubusercontent.com/23468631/128293314-0c8e9976-ebaf-48a2-bbf6-e7ee0fd69e2b.png)

Do I need special permissions to install from master?

**Comment by zwaldowski** [comment]
Oh, nuts. Sorry about that. It's trying to check out over [SSH](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/about-ssh) as though you are an author of the repo. That's not really something on my end, it's how GitHub is designed.

Try instead:

```
npm install -g homebridge git+https://github.com/zwaldowski/homebridge-satellite-fan.git#master
```

… what a mouthful!

**Comment by viictor924** [comment]
I got the same error again (code 128) :(

![image](https://user-images.githubusercontent.com/23468631/128393591-12222060-dc4e-4e83-b1b5-51d02cf0e8fb.png)

**Comment by zwaldowski** [comment]
Ah, towards the end `command git` shows it actually did the exact same thing as before. Dumb. We have to go simpler. 😝

```
npm install -g homebridge https://github.com/zwaldowski/homebridge-satellite-fan
```

That works on my side.

**Comment by viictor924** [comment]
Alright, I followed these instructions to add a new SSH key to my github account.
https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

Before adding the key the error looked like this:
![image](https://user-images.githubusercontent.com/23468631/128411200-b377b916-8fd0-4138-ac1e-6561e13fff50.png)

After adding the key the error now looks like this:
![image](https://user-images.githubusercontent.com/23468631/128412056-b4fe1661-91c2-48e9-982a-03d632cb184e.png)
I'm reading a bit on the error and some people have suggested downloading the master.zip file from the git repo instead of using npm. Thoughts?

**Comment by zwaldowski** [comment]
OK, as I alluded to up [here](https://github.com/zwaldowski/homebridge-satellite-fan/issues/13#issuecomment-892348687), the `could not create leading directories` has nothing to do with this repo or plugin, so I'm limited in how much I can help.

You can try clearing that cache directory (`sudo rm -rf /root/.npm`) to see if it works just by trying again. Otherwise, at that point I'm a little out of my depth and the Homebridge [Discord](https://github.com/homebridge/homebridge#community) might be able to get you better help.
